version: '3'
services:
  server:
    build: .
    image: expenses-api
    container_name: expenses_api
    command: npm start
    ports:
      - '8080:8080'
    volumes:
      - '${PWD}:/usr/src/app'
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mongo
